spring:
  profiles:
    active: dev
  application:
    name: jingxc-boot-google
server:
  port: 8092
  servlet:
    context-path: /jingxc/google
  tomcat:
    threads:
      max: 1000
    max-connections: 20000
  forward-headers-strategy: native
