spring:
  profiles:
    active: dev
  application:
    name: jingxc-boot-rabbitmq-producer
server:
  port: 8096
  servlet:
    context-path: /jingxc/rabbitmq
  tomcat:
    threads:
      max: 1000
    max-connections: 20000
  forward-headers-strategy: native
