spring:
  profiles:
    active: dev
  application:
    name: jingxc-boot-paypal
server:
  port: 8091
  servlet:
    context-path: /jingxc/xsolla
  tomcat:
    threads:
      max: 1000
    max-connections: 20000
  forward-headers-strategy: native
