server:
  port: 8089
  servlet:
    context-path: /jingxc/sharding/sphere
spring:
  profiles:
    active: dev
  application:
    name: jingxc-boot-sharding-sphere
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml