spring:
  profiles:
    active: dev
  application:
    name: jingxc-spring-boot-google
server:
  port: 8093
  servlet:
    context-path: /jingxc/facebook
  tomcat:
    threads:
      max: 1000
    max-connections: 20000
  forward-headers-strategy: native
