spring:
  profiles:
    active: dev
  application:
    name: jingxc-spring-boot-es
  elasticsearch:
    rest:
      uris: 127.0.0.1:9201
server:
  port: 8098
  servlet:
    context-path: /jingxc/elastic/search
  tomcat:
    threads:
      max: 1000
    max-connections: 20000
  forward-headers-strategy: native
