spring:
  profiles:
    active: dev
  application:
    name: jingxc-boot-apple
server:
  port: 8093
  servlet:
    context-path: /jingxc/apple
  tomcat:
    threads:
      max: 1000
    max-connections: 20000
  forward-headers-strategy: native
